http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager-core
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=you@example.com
user.name=Hermes222
core.editor=code --wait
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.Hermes.url=https://github.com/Hermes222/01-starting.git
remote.Hermes.fetch=+refs/heads/*:refs/remotes/Hermes/*
remote.app-project.url=https://github.com/Hermes222/01-starting.git
remote.app-project.fetch=+refs/heads/*:refs/remotes/app-project/*
remote.origin.url=https://github.com/Hermes222/01-starting-setup.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.stuff.url=https://github.com/Hermes222/01-starting.git
remote.stuff.fetch=+refs/heads/*:refs/remotes/stuff/*
remote.project1.url=https://github.com/Hermes222/crispy-waddle.git
remote.project1.fetch=+refs/heads/*:refs/remotes/project1/*
